server:
  port: 9090

spring:
  application:
    name: my_edms

  datasource:
    url: jdbc:mysql://localhost:3307/edms
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

minio:
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: documents

elasticsearch:
  host: http://localhost:9200

